name: build oses
on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * 1"
  push:
    branches:
      - master
    paths:
      - oses/**
jobs:
  push:
    name: "yolks:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oses:
          - alpine
          - debian
          - ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./oses/${{ matrix.oses }}
          file: ./oses/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/pterodactyl-images/yolks:${{ matrix.oses }}
